name: Fetch and Process Nodes

on:
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Fetch and process nodes
      run: python scripts/fetch_nodes.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add nodes/
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update nodes data [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push
